channel_sources:
  - nsls2forge,defaults
channel_targets:
  - nsls2forge main
cdt_name:
  - cos6
numpy:
  - 1.16
  - 1.16
  - 1.16
python:
  - 3.7
  - 3.8
  - 3.9
python_impl:
  - cpython
  - cpython
  - cpython
