{% set name = "xraylarch" %}
{% set version = "0.9.48" %}
{% set sha256 = "f9b9a3b1d3bbfbec2829e208c01a36b76067f1ae6b9949e05ebb5ddff70a9171" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xraypy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-MNT-remove-the-desktop-shortcut-logic.patch
    - 0002-MNT-remove-the-feff-wrappers-and-binaries.patch

build:
  number: 0
  script: |
    # We do not have a license to distribute built FEFF binaries.
    # We may have one to deploy it to the floor, but definitely not to make
    # them public, so remove binaries.
    rm -rf larch/bin  # [not win]
    rmdir /q /s larch/bin  # [win]
    {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - asteval >=0.9.18
    - fabio
    - h5py >=2.8
    - lmfit >=1.0
    - matplotlib >=3.0
    - numpy >=1.7
    - peakutils >=1.0.0
    - pillow >=3.4
    - psutil
    - pyFAI
    - pyyaml
    - requests >=2.1
    - scikit-image
    - scikit-learn
    - scipy >=1.2
    - silx
    - six >=1.10
    - sqlalchemy >=0.9
    - termcolor
    - uncertainties
    - wxmplot
    - wxpython
    - wxutils
    - xraydb >=4.3

test:
  imports:
    - larch

about:
  home: https://xraypy.github.io/xraylarch
  license: BSD-2
  license_file: LICENSE
  summary: 'Larch: X-ray Analysis for Synchrotron Applications using Python'
  doc_url: https://xraypy.github.io/xraylarch
  dev_url: https://github.com/xraypy/xraylarch
